### PR TITLE
ci: Autoformatting and refactoring

### PR DESCRIPTION
**Pull request by Moffinguer**
Create an autoformatter

### Affected module(s) system

CI

### Description of change

Hook to format and refactor code

### CODE REVIEW

**Review by adrrf — APPROVED** [review]
resuelve los conflictos, y todo en orden

**Comment by Moffinguer** [comment]
Errores solventados

**Review by dangalmar — APPROVED** [review]

**Review by carlos-bermejo — APPROVED** [review]
It looks like the formatting works alright.

**Review by carzarrei — APPROVED** [review]
Todo correcto

**Review by Francisco-David — APPROVED** [review]

**Pull request merged**
